# This is a basic workflow to help you get started with Actions

name: Deploy APIM Api definitions
on:
  workflow_dispatch:
    inputs:
      resourcegroup:
        description: "Resource Group to deploy to"
        default: "team2App-devenv"
        required: true
        type: choice
        options: 
        - team2App-devenv
        - team2App-bluedevenv
        - team2App-greendevenv
        
      apimname:
        description: "API Management Instance Name"
        default: "apim-icecream"
        required: true
        type: choice
        options: 
        - apim-icecream
        - apim-icecreamgreen-nxwhongiagiiu
        - apim-icecreamblue-3plwdf5dpxexw
        
      ratingsapiurl:
        description: "Ratings Api Url"
        default: "https://app-ratings-fi4a3nk4vlrka.azurewebsites.net/api"
        required: true
        type: choice
        options: 
        - "https://app-ratings-vsabv73meajog.azurewebsites.net/api"
        - "https://app-ratings-fi4a3nk4vlrka.azurewebsites.net/api"
        
env:
  DEPNAME: "DepApi${{ github.run_number }}" #Deployment Name
  AZCLIVERSION: latest #2.30.0 #Pinning to a specific AZ CLI version

concurrency: github.event.inputs.resourcegroup

jobs:
  DeployAPIs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Job parameter check
        run: |       
          echo "RG is: ${{ github.event.inputs.resourcegroup }}"
          
          echo "APIMName is: ${{ github.event.inputs.apimname }}"
          echo "Ratings url is: ${{ github.event.inputs.ratingsapiurl }}"
          echo "Deployment name is ${{ env.DEPNAME }}"
          echo "Ref is ${{ github.ref }}"
          echo "EventTrigger name is ${{github.event_name}}"
          echo "AZCLIVERSION is ${{ env.AZCLIVERSION }}"
          
          echo "Inputs are ${{ tojson(github.event.inputs) }}"
          
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
          environment: azurecloud
          allow-no-subscriptions: false
          
      - name: Validate Infrastructure deployment
        uses: Azure/cli@1.0.4
        with:
          azcliversion: ${{ env.AZCLIVERSION }}
          inlineScript: |
            RG='${{ github.event.inputs.ResourceGroup }}'
            APIMNAME='${{ github.event.inputs.APIMName }}'
            RATINGSURL='${{ github.event.inputs.ratingsapiurl }}'
            
            az deployment group validate -f apim-apis.bicep -g $RG -p apimName=$APIMNAME ratingsApiBaseUrl="$RATINGSURL"
          
      - name: Deploy Infrastructure
        id: deployInfra
        uses: Azure/cli@1.0.4
        with:
          azcliversion: ${{ env.AZCLIVERSION }}
          inlineScript: |
            RG='${{ github.event.inputs.ResourceGroup }}'
            APIMNAME='${{ github.event.inputs.APIMName }}'
            RATINGSURL='${{ github.event.inputs.ratingsapiurl }}'
            
            az deployment group create -f apim-apis.bicep -g $RG -p apimName=$APIMNAME ratingsApiBaseUrl="$RATINGSURL" --name $DEPNAME
            
            DEPSTATUS=$(az deployment operation group list --resource-group $RG --name $DEPNAME) #--query "[?properties.provisioningState=='Failed']"
            echo $DEPSTATUS
            
             
