# This is a basic workflow to help you get started with Actions

name: Deploy Infra
on:
  workflow_dispatch:
    inputs:
      RG:
        description: "Resource Group to deploy to"
        default: "team2App-devenv"
        required: true
        
      AppNameSpeed:
        description: "App Name Seed"
        default: "Ratings"
        required: true
        
      ApimNameSeed:
        description: "App Name Seed"
        default: "icecream"
        required: true
        
env:
  #RG: "team2App-devenv" #The resource group we're deploying to.
  #ParamFilePath: ".github/workflows_dep/AksDeploy-Basic.parameters.json" #Path to parameter file
  #RESNAME: "Ratings" #Used in Azure Resource Naming, overrides the default in the parameter file
  DEPNAME: "Dep${{ github.run_number }}" #Deployment Name
  AZCLIVERSION: latest #2.30.0 #Pinning to a specific AZ CLI version

concurrency: github.event.inputs.RG

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Job parameter check
        run: |       
          echo "RG is: ${{ github.event.inputs.RG }}"
          
          echo "AppNameSpeed is: ${{ github.event.inputs.AppNameSpeed }}"
          echo "ApimNameSeed is: ${{ github.event.inputs.ApimNameSeed }}"
          echo "Deployment name is ${{ env.DEPNAME }}"
          echo "Ref is ${{ github.ref }}"
          echo "EventTrigger name is ${{github.event_name}}"
          echo "AZCLIVERSION is ${{ env.AZCLIVERSION }}"
          
          echo "Inputs are ${{ tojson(github.event.inputs) }}"
          
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
          environment: azurecloud
          allow-no-subscriptions: false
          
      - name: Validate Infrastructure deployment
        uses: Azure/cli@1.0.4
        with:
          azcliversion: ${{ env.AZCLIVERSION }}
          inlineScript: |
            RG="${{ github.event.inputs.RG }}"
            RESNAME="${{ github.event.inputs.AppNameSpeed }}"
            APIMNAMESEED="${{ github.event.inputs.ApimNameSeed }}"

            az deployment group validate -f main.bicep -g $RG -p appName=$RESNAME apimNameSeed=$APIMNAMESEED
          
      - name: Deploy Infrastructure
        id: deployInfra
        uses: Azure/cli@1.0.4
        with:
          azcliversion: ${{ env.AZCLIVERSION }}
          inlineScript: |
            RG="${{ github.event.inputs.RG }}"
            RESNAME="${{ github.event.inputs.AppNameSpeed }}"
            APIMNAMESEED="${{ github.event.inputs.ApimNameSeed }}"
            
            az deployment group create -f main.bicep -g $RG -p appName=$RESNAME  apimNameSeed=$APIMNAMESEED --name $DEPNAME 
            
            DEPSTATUS=$(az deployment operation group list --resource-group $RG --name $DEPNAME) #--query "[?properties.provisioningState=='Failed']"
            echo $DEPSTATUS
            
            #outputs
            APPURL=$(az deployment group show -n $DEPNAME -g $RG --query "properties.outputs.appUrl.value" -o tsv)
            echo "APPURL returned from az deployment = $APPURL"
            echo "::set-output name=APPURL::$APPURL"
            
            APPNAME=$(az deployment group show -n $DEPNAME -g $RG --query "properties.outputs.appName.value" -o tsv)
            echo "APPNAME returned from az deployment = $APPNAME"
            echo "::set-output name=APPNAME::$APPNAME"
             
